"""FastAPI app exposing the Cytation 5 service over the lab status spec v1.1.

Endpoints
---------

Spec-mandated read surface (always available):

* ``GET /``             -- cheap probe: :class:`ProbeResponse`
* ``GET /health``       -- liveness:    :class:`HealthResponse`
* ``GET /status``       -- full :class:`EquipmentStatus` envelope
                            (side-effect-free, always 200 unless the
                            process is broken)
* ``GET /openapi.json`` -- generated by FastAPI

v1.1 claim protocol:

* ``POST /control/claim``      -- acquire a cooperative claim
* ``POST /control/heartbeat``  -- refresh the claim's TTL (X-Claim-Token)
* ``POST /control/release``    -- release the claim (X-Claim-Token)

v1.1 control verbs (all require ``X-Claim-Token`` when claims are
enforced; the service rejects with HTTP 423 Locked otherwise):

* ``POST /control/startup``               -- connect to hardware
* ``POST /control/shutdown``              -- disconnect
* ``POST /control/drawer/open``           -- eject plate
* ``POST /control/drawer/close``          -- retract plate
* ``POST /control/plate/load``            -- register a loaded plate
* ``POST /control/plate/unload``          -- clear the loaded plate
* ``POST /control/well/update``           -- mutate one well
* ``POST /control/read/absorbance``       -- absorbance read
* ``POST /control/read/fluorescence``     -- fluorescence read
* ``POST /control/read/luminescence``     -- luminescence read
* ``POST /control/imaging/capture``       -- capture one image

Auth: none at the device level; access is gated by Tailscale ACLs.
CORS: wildcard by default; tighten via ``[service] cors_origins`` in
``config.toml`` if the device ever leaves the Tailnet.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException, Header, Response, status as http_status
from fastapi.middleware.cors import CORSMiddleware

from . import config as _config
from .claims import ClaimManager, ClaimRejectedError
from .control_args import (
    AbsorbanceArgs,
    DrawerArgs,
    FluorescenceArgs,
    ImagingCaptureArgs,
    ImagingCaptureResponse,
    LuminescenceArgs,
    PlateLoadArgs,
    ReadResponse,
    WellUpdateArgs,
)
from .models import (
    PROTOCOL_VERSION,
    ClaimRejection,
    ClaimRequest,
    ClaimResponse,
    EquipmentStatus,
    HealthResponse,
    LoadedPlate,
    ProbeResponse,
    WellSample,
)
from .plate_state import PlateStateStore
from .service import CytationService

logger = logging.getLogger(__name__)


def create_app(
    *,
    dry_run: bool | None = None,
    plate_state: PlateStateStore | None = None,
    claim_manager: ClaimManager | None = None,
) -> FastAPI:
    """Build the FastAPI application.

    Parameters
    ----------
    dry_run:
        Force dry-run mode regardless of ``config.toml``. ``None`` means
        "use the config file". Tests pass ``True`` to keep CI hardware-free.
    plate_state:
        Optional pre-constructed :class:`PlateStateStore` (tests use a
        ``tmp_path``-scoped store; production builds one from
        ``[plates].state_path`` in ``config.toml``).
    claim_manager:
        Optional pre-constructed :class:`ClaimManager`; tests inject one
        with ``enforce=False`` to bypass the X-Claim-Token gate.
    """
    if dry_run is None:
        dry_run = bool(_config.get("service", "dry_run", False))

    service = CytationService(
        dry_run=dry_run,
        plate_state=plate_state,
        claim_manager=claim_manager,
    )
    startup_timeout = float(_config.get("service", "startup_connect_timeout_s", 30.0))

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        # Best-effort connect on startup. If the device is unreachable
        # (powered off, USB not bound to libusbK, pylabrobot missing) we
        # log and leave the service in `requires_init`; the dashboard
        # tile renders that state cleanly.
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("Cytation auto-connect succeeded")
        except asyncio.TimeoutError:
            logger.warning(
                "Cytation connect timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("Cytation auto-connect failed: %s", exc)
        try:
            yield
        finally:
            await service.shutdown()

    app = FastAPI(
        title="BioTek (Agilent) Cytation 5 — REST API",
        version="0.2.0",
        description=(
            "REST API for the BioTek / Agilent Cytation 5 plate reader. "
            "Conforms to the AC lab equipment status spec v1.1 — see "
            "`docs/STATUS_SPEC.md` in the ac-organic-lab monorepo. "
            "Driver layer is PyLabRobot's `PlateReader` + `Cytation5Backend`."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get("service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ------------------------------------------------------------------
    # Spec read surface
    # ------------------------------------------------------------------

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    # ------------------------------------------------------------------
    # Claim protocol (v1.1)
    # ------------------------------------------------------------------

    @app.post(
        "/control/claim",
        response_model=ClaimResponse,
        tags=["claim"],
    )
    async def claim(body: ClaimRequest) -> ClaimResponse:
        try:
            token, hb, expires = service.claims.claim(
                owner=body.owner, session_id=body.session_id, ttl_s=body.ttl_s
            )
        except ClaimRejectedError as exc:
            raise HTTPException(
                status_code=http_status.HTTP_409_CONFLICT,
                detail=ClaimRejection(
                    detail=exc.detail,
                    claimed_by=exc.claimed_by,
                    retry_after_s=exc.retry_after_s,
                ).model_dump(mode="json"),
                headers=(
                    {"Retry-After": str(int(exc.retry_after_s))}
                    if exc.retry_after_s
                    else None
                ),
            ) from exc
        return ClaimResponse(
            claim_token=token, heartbeat_interval_s=hb, expires_at=expires
        )

    @app.post("/control/heartbeat", tags=["claim"])
    async def heartbeat(
        x_claim_token: str = Header(..., alias="X-Claim-Token"),
    ) -> Response:
        try:
            service.claims.heartbeat(x_claim_token)
        except ClaimRejectedError as exc:
            raise HTTPException(
                status_code=http_status.HTTP_401_UNAUTHORIZED, detail=exc.detail
            ) from exc
        return Response(status_code=http_status.HTTP_204_NO_CONTENT)

    @app.post("/control/release", tags=["claim"])
    async def release(
        x_claim_token: str = Header(..., alias="X-Claim-Token"),
    ) -> Response:
        # Idempotent: never raises -- if the token is unknown, the
        # client moves on.
        service.claims.release(x_claim_token)
        return Response(status_code=http_status.HTTP_204_NO_CONTENT)

    # ------------------------------------------------------------------
    # /control/* dispatch
    # ------------------------------------------------------------------

    def _enforce_claim(token: str | None) -> None:
        if not service.claims.enforce:
            return
        if not service.claims.matches(token):
            holder = service.claims.current()
            raise HTTPException(
                status_code=http_status.HTTP_423_LOCKED,
                detail=ClaimRejection(
                    detail=(
                        "Missing or invalid X-Claim-Token. "
                        "POST /control/claim first."
                    ),
                    claimed_by=holder,
                ).model_dump(mode="json"),
            )

    def _wrap_runtime(exc: Exception) -> HTTPException:
        return HTTPException(
            status_code=http_status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )

    # ---- lifecycle --------------------------------------------------

    @app.post("/control/startup", tags=["control"])
    async def control_startup(
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> Response:
        _enforce_claim(x_claim_token)
        try:
            await service.startup()
        except Exception as exc:  # hardware errors -> 503
            raise _wrap_runtime(exc) from exc
        return Response(status_code=http_status.HTTP_204_NO_CONTENT)

    @app.post("/control/shutdown", tags=["control"])
    async def control_shutdown(
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> Response:
        _enforce_claim(x_claim_token)
        await service.shutdown()
        return Response(status_code=http_status.HTTP_204_NO_CONTENT)

    # ---- drawer -----------------------------------------------------

    @app.post("/control/drawer/open", tags=["control"])
    async def control_drawer_open(
        body: DrawerArgs = DrawerArgs(),  # noqa: B008 - intentional default
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> Response:
        _enforce_claim(x_claim_token)
        try:
            await service.open_drawer()
        except Exception as exc:
            raise _wrap_runtime(exc) from exc
        return Response(status_code=http_status.HTTP_204_NO_CONTENT)

    @app.post("/control/drawer/close", tags=["control"])
    async def control_drawer_close(
        body: DrawerArgs = DrawerArgs(),  # noqa: B008 - intentional default
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> Response:
        _enforce_claim(x_claim_token)
        try:
            await service.close_drawer()
        except Exception as exc:
            raise _wrap_runtime(exc) from exc
        return Response(status_code=http_status.HTTP_204_NO_CONTENT)

    # ---- plate / wells ---------------------------------------------

    @app.post(
        "/control/plate/load",
        response_model=LoadedPlate,
        tags=["control"],
    )
    async def control_plate_load(
        body: PlateLoadArgs,
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> LoadedPlate:
        _enforce_claim(x_claim_token)
        try:
            return await service.load_plate(
                plate_id=body.plate_id,
                model=body.model,
                wells=body.wells,
            )
        except ValueError as exc:
            raise HTTPException(
                status_code=http_status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=str(exc),
            ) from exc

    @app.post(
        "/control/plate/unload",
        response_model=LoadedPlate | None,
        tags=["control"],
    )
    async def control_plate_unload(
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> LoadedPlate | None:
        _enforce_claim(x_claim_token)
        return await service.unload_plate()

    @app.post(
        "/control/well/update",
        response_model=WellSample,
        tags=["control"],
    )
    async def control_well_update(
        body: WellUpdateArgs,
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> WellSample:
        _enforce_claim(x_claim_token)
        try:
            return await service.update_well(
                body.well,
                sample_id=body.sample_id,
                volume_ul=body.volume_ul,
                notes=body.notes,
                clear_sample_id=body.clear_sample_id,
                clear_notes=body.clear_notes,
            )
        except (LookupError, ValueError) as exc:
            # LookupError -> no plate loaded / unknown well -> 409 or 422
            code = (
                http_status.HTTP_409_CONFLICT
                if isinstance(exc, LookupError)
                else http_status.HTTP_422_UNPROCESSABLE_ENTITY
            )
            raise HTTPException(status_code=code, detail=str(exc)) from exc

    # ---- reads ------------------------------------------------------

    @app.post(
        "/control/read/absorbance",
        response_model=ReadResponse,
        tags=["control"],
    )
    async def control_read_absorbance(
        body: AbsorbanceArgs,
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> ReadResponse:
        _enforce_claim(x_claim_token)
        try:
            wells = await service.read_absorbance(
                wells=body.wells, wavelength_nm=body.wavelength_nm
            )
        except Exception as exc:
            raise _wrap_runtime(exc) from exc
        return ReadResponse(wells=wells)

    @app.post(
        "/control/read/fluorescence",
        response_model=ReadResponse,
        tags=["control"],
    )
    async def control_read_fluorescence(
        body: FluorescenceArgs,
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> ReadResponse:
        _enforce_claim(x_claim_token)
        try:
            wells = await service.read_fluorescence(
                wells=body.wells,
                excitation_nm=body.excitation_nm,
                emission_nm=body.emission_nm,
                gain=body.gain,
                focal_height_mm=body.focal_height_mm,
            )
        except Exception as exc:
            raise _wrap_runtime(exc) from exc
        return ReadResponse(wells=wells)

    @app.post(
        "/control/read/luminescence",
        response_model=ReadResponse,
        tags=["control"],
    )
    async def control_read_luminescence(
        body: LuminescenceArgs,
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> ReadResponse:
        _enforce_claim(x_claim_token)
        try:
            wells = await service.read_luminescence(
                wells=body.wells,
                integration_time_s=body.integration_time_s,
                gain=body.gain,
            )
        except Exception as exc:
            raise _wrap_runtime(exc) from exc
        return ReadResponse(wells=wells)

    # ---- imaging ----------------------------------------------------

    @app.post(
        "/control/imaging/capture",
        response_model=ImagingCaptureResponse,
        tags=["control"],
    )
    async def control_imaging_capture(
        body: ImagingCaptureArgs,
        x_claim_token: str | None = Header(default=None, alias="X-Claim-Token"),
    ) -> ImagingCaptureResponse:
        _enforce_claim(x_claim_token)
        try:
            payload = await service.capture_image(
                well=body.well,
                channel=body.channel,
                focal_height_mm=body.focal_height_mm,
                exposure_ms=body.exposure_ms,
                gain=body.gain,
            )
        except Exception as exc:
            raise _wrap_runtime(exc) from exc
        return ImagingCaptureResponse(
            well=body.well,
            channel=body.channel,
            focal_height_mm=body.focal_height_mm,
            exposure_ms=body.exposure_ms,
            gain=body.gain,
            details={
                k: v
                for k, v in payload.items()
                if k not in {"well", "channel", "focal_height_mm", "exposure_ms", "gain"}
            },
        )

    # Expose the service for tests / debugging — standard FastAPI pattern.
    app.state.service = service
    return app


__all__ = ["create_app"]
