"""FastAPI app exposing the Cytation 5 service over the lab status spec v1.0.

Endpoints
---------

Spec-mandated (always available):

* ``GET /``         - cheap probe: :class:`ProbeResponse`
* ``GET /health``   - liveness:    :class:`HealthResponse`
* ``GET /status``   - full :class:`EquipmentStatus` envelope
                       (side-effect-free, always 200 unless the process
                       is broken)
* ``GET /openapi.json`` - generated by FastAPI

There is no ``/control/*`` surface yet. Specific unit operations
(``read.*``, ``imaging.capture``, ``plate.load`` / ``plate.unload``,
``drawer.open`` / ``drawer.close``) are promoted to ``/control/*`` and
the spec bumps to v1.1 (claim/heartbeat/release) in a follow-up.

Auth: none at the device level; access is gated by Tailscale ACLs.
CORS: wildcard by default; tighten via ``[service] cors_origins`` in
``config.toml`` if the device ever leaves the Tailnet.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from . import config as _config
from .models import (
    PROTOCOL_VERSION,
    EquipmentStatus,
    HealthResponse,
    ProbeResponse,
)
from .service import CytationService

logger = logging.getLogger(__name__)


def create_app(
    *,
    dry_run: bool | None = None,
) -> FastAPI:
    """Build the FastAPI application.

    Parameters
    ----------
    dry_run:
        Force dry-run mode regardless of ``config.toml``. ``None`` means
        "use the config file". Tests pass ``True`` to keep CI hardware-free.
    """
    if dry_run is None:
        dry_run = bool(_config.get("service", "dry_run", False))

    service = CytationService(dry_run=dry_run)
    startup_timeout = float(_config.get("service", "startup_connect_timeout_s", 30.0))

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        # Best-effort connect on startup. If the device is unreachable
        # (powered off, USB not bound to libusbK, pylabrobot missing) we
        # log and leave the service in `requires_init`; the dashboard
        # tile renders that state cleanly.
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("Cytation auto-connect succeeded")
        except asyncio.TimeoutError:
            logger.warning(
                "Cytation connect timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("Cytation auto-connect failed: %s", exc)
        try:
            yield
        finally:
            await service.shutdown()

    app = FastAPI(
        title="BioTek (Agilent) Cytation 5 — REST API",
        version="0.1.0",
        description=(
            "Read-only REST API for the BioTek / Agilent Cytation 5 plate "
            "reader. Conforms to the AC lab equipment status spec v1.0 — "
            "see `docs/STATUS_SPEC.md` in the ac-organic-lab monorepo. "
            "Driver layer is PyLabRobot's `PlateReader` + `Cytation5Backend`."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get("service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    # Expose the service for tests / debugging — same pattern as
    # agilent_plateloc/src/agilent_plateloc/api.py.
    app.state.service = service
    return app


__all__ = ["create_app"]
